forward_joint_trajectories:
    type: "joint_trajectory_controllers/PassThroughController"
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6

forward_cartesian_trajectories:
    type: "cartesian_trajectory_controllers/PassThroughController"
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6

joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
